// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20200816175924_RegistrovaniKorisnici")]
    partial class RegistrovaniKorisnici
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Klase.RegistrovaniKorisniciKlasa", b =>
                {
                    b.Property<string>("eadresaProvera")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("gradProvera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imeProvera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lozinkaProvera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prezimeProvera")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("telefonProvera")
                        .HasColumnType("bigint");

                    b.HasKey("eadresaProvera");

                    b.ToTable("RegistrovaniKorisnici");
                });
#pragma warning restore 612, 618
        }
    }
}
